version: '3.7'

services:
    mongodb:
        image: mvertes/alpine-mongo
        expose:
            - "27017"
        volumes:
            -  ./ofertascrawler/data/mongodb:/data/db
        restart: always

    crawler:
        build: ./ofertascrawler
        depends_on:
            - mongodb
        restart: on-failure

    flask:
        build: ./flask-api
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        restart: always
