version: '3'

services:
    mongo:
        image: mvertes/alpine-mongo
        expose:
            - "27017"
        volumes:
            -  ./ofertascrawler/data/mongodb:/data/db

    crawler:
        build: ./ofertascrawler
        depends_on:
            - mongo
        volumes:
            - ./ofertascrawler/.scrapy/:/ofertascrawler/.scrapy/
        restart: always
    
    flask:
        build: ./flask-api
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        restart: always
